# Generated by Django 3.0.8 on 2020-07-27 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=40)),
                ('piqlConnect_1TB_120GB_in_EUR_per_yr', models.FloatField(default=8880)),
                ('online_data_in_GB', models.FloatField()),
                ('online_sales_price_EUR_per_GB', models.FloatField(default=0.07)),
                ('offline_data_in_GB', models.FloatField()),
                ('offline_sales_price_EUR_per_GB', models.FloatField(default=15)),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('partner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
