# Generated by Django 3.0.8 on 2020-07-28 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=40, verbose_name='Client')),
                ('offline_data', models.FloatField(default=0, verbose_name='Offline data (GB)')),
                ('online_data', models.FloatField(default=0, verbose_name='Online data (GB)')),
                ('type', models.CharField(blank=True, choices=[('digital', 'Digital'), ('visual', 'Visual'), ('hybrid', 'Hybrid')], max_length=40, verbose_name='Type of preservation')),
                ('pages', models.IntegerField(blank=True, default=0, verbose_name='How many pages')),
                ('layout', models.CharField(blank=True, choices=[('1', '1 page'), ('2', '2 pages'), ('3', '3 pages'), ('4', '4 page'), ('6', '6 pages'), ('10', '10 pages')], max_length=40, verbose_name='Pages per frame')),
                ('payment', models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('only_piqlfilm', 'Only piqlFilm')], max_length=40)),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('partner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
