# Generated by Django 3.0.8 on 2020-07-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='layout',
            field=models.CharField(blank=True, choices=[('1', '1 page'), ('2', '2 pages'), ('3', '3 pages'), ('4', '4 page'), ('6', '6 pages'), ('10', '10 pages')], default='digital', max_length=40, verbose_name='Pages per frame'),
        ),
    ]
