# Generated by Django 3.0.8 on 2020-07-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20200729_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='layout',
            field=models.CharField(blank=True, choices=[('1', '1 page'), ('2', '2 pages'), ('3', '3 pages'), ('4', '4 page'), ('6', '6 pages'), ('10', '10 pages')], default='1', max_length=40, verbose_name='Pages per frame'),
        ),
        migrations.AlterField(
            model_name='input',
            name='type',
            field=models.CharField(blank=True, choices=[('digital', 'Digital'), ('visual', 'Visual'), ('hybrid', 'Hybrid')], default='digital', max_length=40, verbose_name='Type of preservation'),
        ),
    ]
