# Generated by Django 3.0.8 on 2020-07-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20200729_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='offline_data',
            field=models.IntegerField(default=0, verbose_name='Offline data (GB)'),
        ),
        migrations.AlterField(
            model_name='input',
            name='online_data',
            field=models.IntegerField(default=0, verbose_name='Online data (GB)'),
        ),
    ]
