# Generated by Django 3.0.8 on 2020-08-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20200731_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='awa',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=40, verbose_name='Storage in Arctic World Archive'),
        ),
        migrations.AddField(
            model_name='input',
            name='awa_contribution',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=40, verbose_name='Entity'),
        ),
        migrations.AddField(
            model_name='input',
            name='awa_mgmt_fee',
            field=models.IntegerField(default=60, verbose_name='AWA Management fee (yearly)'),
        ),
        migrations.AddField(
            model_name='input',
            name='awa_reg_fee',
            field=models.IntegerField(default=200, verbose_name='AWA Registration fee'),
        ),
        migrations.AddField(
            model_name='input',
            name='awa_storage',
            field=models.CharField(choices=[('5', '5 years'), ('10', '10 years'), ('25', '25 years')], default='gold', max_length=40, verbose_name='AWA Storage'),
        ),
        migrations.AddField(
            model_name='input',
            name='piqlreader',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=40, verbose_name='piqlReader'),
        ),
        migrations.AddField(
            model_name='input',
            name='service',
            field=models.CharField(blank=True, choices=[('platinum', 'Platinum'), ('gold', 'Gold')], max_length=40, verbose_name='Service agreement'),
        ),
        migrations.AlterField(
            model_name='input',
            name='comment',
            field=models.TextField(verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='input',
            name='pages',
            field=models.IntegerField(blank=True, default=0, verbose_name='Offline visual (pages)'),
        ),
        migrations.AlterField(
            model_name='input',
            name='payment',
            field=models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('only_piqlfilm', 'Only piqlFilm')], max_length=40, verbose_name='Online payment'),
        ),
        migrations.AlterField(
            model_name='input',
            name='type',
            field=models.CharField(blank=True, choices=[('digital', 'Digital'), ('visual', 'Visual'), ('hybrid', 'Hybrid')], default='digital', max_length=40, verbose_name='Type of offline preservation'),
        ),
    ]
