# Generated by Django 3.0.8 on 2020-08-23 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20200823_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='awa_mgmt_fee',
        ),
        migrations.RemoveField(
            model_name='input',
            name='awa_reg_fee',
        ),
    ]
