# Generated by Django 3.0.8 on 2020-08-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_auto_20200824_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='consultancy',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=40, verbose_name='Professional services'),
        ),
        migrations.AddField(
            model_name='input',
            name='days',
            field=models.IntegerField(blank=True, default='1', verbose_name='How many days?'),
        ),
    ]
