# Generated by Django 3.0.8 on 2020-08-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_auto_20200825_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='quantity',
            field=models.IntegerField(blank=True, default='1', verbose_name='Quantity of piqlReaders'),
        ),
    ]
