# Generated by Django 3.0.8 on 2020-08-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_input_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='consultancy',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=40, verbose_name='Professional services'),
        ),
        migrations.AlterField(
            model_name='input',
            name='service',
            field=models.CharField(blank=True, choices=[('platinum', 'Platinum'), ('gold', 'Gold')], default='gold', max_length=40, verbose_name='Service agreement'),
        ),
    ]
