# Generated by Django 3.0.8 on 2020-09-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_auto_20200901_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='awa',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=40, verbose_name='Storage in Arctic World Archive'),
        ),
        migrations.AlterField(
            model_name='input',
            name='consultancy',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=40, verbose_name='Professional services'),
        ),
        migrations.AlterField(
            model_name='input',
            name='days',
            field=models.IntegerField(default=1, verbose_name='How many days?'),
        ),
        migrations.AlterField(
            model_name='input',
            name='layout',
            field=models.CharField(choices=[('1', '1 page'), ('2', '2 pages'), ('3', '3 pages'), ('4', '4 page'), ('6', '6 pages'), ('10', '10 pages')], default='1', max_length=40, verbose_name='Pages per frame'),
        ),
        migrations.AlterField(
            model_name='input',
            name='pages',
            field=models.IntegerField(default=0, verbose_name='Offline visual (pages)'),
        ),
        migrations.AlterField(
            model_name='input',
            name='piqlreader',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=40, verbose_name='piqlReader'),
        ),
        migrations.AlterField(
            model_name='input',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity of piqlReaders'),
        ),
        migrations.AlterField(
            model_name='input',
            name='service',
            field=models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold')], default='gold', max_length=40, verbose_name='Service agreement'),
        ),
        migrations.AlterField(
            model_name='input',
            name='type',
            field=models.CharField(choices=[('digital', 'Digital'), ('visual', 'Visual'), ('hybrid', 'Hybrid')], default='digital', max_length=40, verbose_name='Type of offline preservation'),
        ),
    ]
