# Generated by Django 3.0.8 on 2020-09-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_auto_20200906_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='awa',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=40, verbose_name='Storage in Arctic World Archive'),
        ),
        migrations.AlterField(
            model_name='input',
            name='consultancy',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=40, verbose_name='Professional services'),
        ),
        migrations.AlterField(
            model_name='input',
            name='piqlreader',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=40, verbose_name='piqlReader'),
        ),
        migrations.AlterField(
            model_name='input',
            name='type',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('visual', 'Visual'), ('digital', 'Digital')], default='hybrid', max_length=40, verbose_name='Type of offline preservation'),
        ),
    ]
