# Generated by Django 3.0.8 on 2020-10-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0014_auto_20200926_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='production',
            field=models.CharField(choices=[('norway', 'Piql Norway'), ('slovakia', 'Piql Slovakia'), ('mexico', 'Piql Mexico')], default='norway', max_length=40, verbose_name='Production partner:'),
        ),
    ]
